### ISSUE TITLE
请问下我该怎么测试我的模型

### ISSUE THREAD

**Issue by wuqi930907** [maozhiqiang/tacotron_cn#4]
是使用griffin_lim_synthesis_example.ipynb来测试训练的模型吗？

**Comment by wuqi930907** [comment]
好的谢谢，十分期待 @maozhiqiang

**Comment by wuqi930907** [comment]
好的，十分感谢，不过还想请教下fft_size，hop_size，frame_length_ms，frame_shift_ms这几个参数该怎么调整呢，他们代表的意思是什么呢？ @maozhiqiang

**Comment by maozhiqiang** [comment]
@wuqi930907  这个最好用默认值, 不要轻易变动 训练  wavenet vocoder时保持一致就行了

**Comment by kismeter** [comment]
@maozhiqiang 目前wavenet vocoder训练结束了吗？效果怎样？
